### ISSUE TITLE
Installation of v1.9.3-1-legacy fails on SFOS2.2.1

### ISSUE THREAD

**Issue by Olf0** [direc85/toeterm#10]
From the [release notes of v1.9.3-1-legacy](https://github.com/direc85/toeterm/releases/tag/v1.9.3-1): "Legacy builds support SailfishOS 2.2 and newer."

After a successful installation on an XperiaX@SFOS3.2.1, I also tried on a Jolla1@SFOS2.2.1, which failed with "Fatal error: nothing provides libc.so.6(GLIBC_2.28) needed by toeterm-1.9.3-1.armv7hl"

Looking at the output of `rpm -qR toeterm-1.9.3-1-legacy.armv7hl.rpm`:
```
...
libc.so.6(GLIBC_2.28)
libc.so.6(GLIBC_2.4)
...
```
This looks wrong to me:
* While there are many references to a `lib*.so.?(GLIBC_2.4)`, there is only this single one to a `lib*.so.?(GLIBC_2.28)`.
* `libc.so.6(GLIBC_2.*)` is the only such "double dependency" on a shared library ("DLL") in two different versions.

**Comment by direc85** [comment]
Thanks for reporting. There must be some sort of a hiccup with that release.

I'll install the SFOS2 build environment and rebuild the packages - and this time I'll test them at my Jolla phone, too.

**Comment by direc85** [comment]
I tried to install the SFOS 2.2.1 build targets, and it borked my whole build engine. Time to reinstall the whole shebang. Again...

I'll have to install the older SDK to another computer, it seems.

**Comment by Olf0** [comment]
Fixed per [toeterm-legacy-1.9.6-1.*.rpm](https://github.com/direc85/toeterm/releases/tag/v1.9.6-1).
Tested installation, configuration and use (the latter only quickly) on a Jolla1 @ SFOS2.2.1 and an XperiaX @ SFOS 3.2.1.

Thank you very much @direc85!
