### ISSUE TITLE
Toeterm lacking --version and --help options.

### ISSUE THREAD

**Issue by hargi** [direc85/toeterm#12]
Trying to find out the version of toeterm I typed in a terminal: 
toeterm --verson
but it responded by opening a terminal window. 
Trying 
toeterm --help 
does the same. 

Maybe adding --version and --help options without opening a terminal would be a thing?

**Comment by direc85** [comment]
Currently it's not possible via terminal, but you can find the version by entering the settings page and selecting about from the pull-down menu.

**Comment by direc85** [comment]
Fixed in version 1.9.12-1
