### ISSUE TITLE
no x86 build available

### ISSUE THREAD

**Issue by piggz** [direc85/toeterm#5]
Could you do an x86 build for jtab, and other x86 sailfish devices?

**Comment by direc85** [comment]
So, i486 build isn't suitable? How can I build for the arch?

**Comment by piggz** [comment]
yes, i486 build is fine..is it already available? didnt appear on my tablet.

**Comment by direc85** [comment]
I don't have a Jolla Tablet to test it with, but I assumed it was fine... Can you install the package manually?

**Comment by piggz** [comment]
It turns out I have it installed, its just that the about page still shows 1.8 not 1.9.... separate issue, the button for the page to the right isnt displayed like it is on the phone.  The old version of toeterm did this too.  Not sure how you can debug it if it works on the phone!

**Comment by direc85** [comment]
I reproduced the issue with the emulator in SDK. I rewrote the component, and now it should work better. Can you test it with the device?

**Comment by piggz** [comment]
Sure, can you send me an rpm?

**Comment by direc85** [comment]
Sorry, I meant that there's an updated version available already in the OpenRepos. Can you update it normally? Does the dot display correctly?

**Comment by piggz** [comment]
Yeah, that looks better!
