### ISSUE TITLE
Functional keys behaving weirdly

### ISSUE THREAD

**Issue by szopin** [direc85/toeterm#7]
When using mc F6 does nothing, F7 acts as F6 and it continues up to F11 which closes mc as if F10, really weird

**Comment by direc85** [comment]
It took me _way longer_ than I expected, but I believe this issue is now fixed. Could you test version 1.9.3 and see if it's fixed now?

Edit: Hopefully fixed in commit 8b671d7

**Comment by szopin** [comment]
Sorry, somehow missed this notification, but it is definitely fixed, thanks!
